// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = "nandana Act";    // Network SSID (name)
const char PASS[]     = "Satish143";    // Network password (use for WPA, or use as key for WEP)

void onMotorChange();
void onWaterpumpChange();

float humidity;
float temperature;
int light;
int moisture;
bool waterpump;
bool motorState;

void initProperties(){

  ArduinoCloud.addProperty(humidity, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(temperature, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(light, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(moisture, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(waterpump, READWRITE, ON_CHANGE, onWaterpumpChange);
  ArduinoCloud.addProperty(motorState, READWRITE, ON_CHANGE, onMotorChange);


}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
